// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trawler.Database;

#nullable disable

namespace Trawler.Database.Migration
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Trawler.Database.Model.CrawlTarget", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("CrawlType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<ulong?>("TargetId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("TargetScreenName")
                        .HasColumnType("longtext");

                    b.Property<ulong?>("WorkaroundPostId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("crawl_targets", (string)null);
                });

            modelBuilder.Entity("Trawler.Database.Model.TwitterAccountCrawlResult", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CrawlDoneAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CrawlDoneAt"));

                    b.Property<uint>("CrawlTargetId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("FollowerCount")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("FollowingCount")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("PostCount")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("twitter_account_crawl_results", (string)null);
                });

            modelBuilder.Entity("Trawler.Database.Model.TwitterPostCrawlResult", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint>("BookmarkCount")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("CrawlDoneAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CrawlDoneAt"));

                    b.Property<uint>("CrawlTargetId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LikesCount")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("PostCreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("QuotesCount")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("RepliesCount")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("RetweetsCount")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("ViewCount")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("CrawlTargetId");

                    b.ToTable("twitter_post_crawl_results", (string)null);
                });

            modelBuilder.Entity("Trawler.Database.Model.TwitterPostCrawlResult", b =>
                {
                    b.HasOne("Trawler.Database.Model.CrawlTarget", "CrawlTarget")
                        .WithMany("CrawlResults")
                        .HasForeignKey("CrawlTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrawlTarget");
                });

            modelBuilder.Entity("Trawler.Database.Model.CrawlTarget", b =>
                {
                    b.Navigation("CrawlResults");
                });
#pragma warning restore 612, 618
        }
    }
}
